# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Firebase Distribution"
  lane :distribute do

    build_android_app(
        task: "assemble",
        flavor: "",
        build_type: "Release",
    )

    commit = last_git_commit
    git_commit = commit[:message]

    firebase_app_distribution(
        app: "1:354081536255:android:64c47ea228acda1f1f74ca",
        groups: "Android",
        release_notes: git_commit
    )
  end
end
